app:
  group: leijendary
  name: @[project.name]
  description: @[project.description]
  version: @[project.version]

spring:
  application:
    name: ${app.name}
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 100
  datasource:
    url:
    username:
    password:
  jpa:
    open-in-view: false
  messages:
    basename: messages.access, messages.error, messages.validation
  security:
    user:
      password: user
  cache:
    type: redis
  cloud:
    stream:
      bindings:
        sampleResponseCreated1-in-0:
          destination: ${app.name}.sample-response.created.v1
        sampleResponseUpdated1-in-0:
          destination: ${app.name}.sample-response.updated.v1
        sampleResponseDeleted1-in-0:
          destination: ${app.name}.sample-response.deleted.v1
      function:
        definition: sampleResponseCreated1;sampleResponseUpdated1;sampleResponseDeleted1
      kafka:
        streams:
          binder:
            functions:
              sampleResponseCreated1:
                application-id: ${app.group}.${app.name}.sample-response.created.v1
              sampleResponseUpdated1:
                application-id: ${app.group}.${app.name}.sample-response.updated.v1
              sampleResponseDeleted1:
                application-id: ${app.group}.${app.name}.sample-response.deleted.v1

ribbon:
  eureka:
    enabled: false

google:
  ribbon:
    listOfServers: https://google.com
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
    retryableStatusCodes: 502,503

logging:
  level:
    com.netflix.config.sources.URLConfigurationSource: ERROR