app:
  group: leijendary
  artifact-id: @[project.artifactId]
  name: @[project.name]
  description: @[project.description]
  version: @[project.version]

spring:
  application:
    name: ${app.name}
  data:
    web:
      pageable:
        max-page-size: 100
  datasource:
    url:
    username:
    password:
  jpa:
    open-in-view: false
  messages:
    basename: messages.access, messages.error, messages.validation
  security:
    user:
      password: user
  cache:
    type: redis
  cloud:
    discovery:
      client:
        simple:
          instances:
            google:
              - uri: https://google.com
    loadbalancer:
      retry:
        max-retries-on-same-service-instance: 3
        retry-on-all-operations: true
        retryable-status-codes: 502,503,521
    service-registry:
      auto-registration:
        enabled: false
    stream:
      bindings:
        sampleResponseCreated1-in-0:
          destination: ${app.artifact-id}.sample-response.created.v1
        sampleResponseUpdated1-in-0:
          destination: ${app.artifact-id}.sample-response.updated.v1
        sampleResponseDeleted1-in-0:
          destination: ${app.artifact-id}.sample-response.deleted.v1
      function:
        definition: sampleResponseCreated1;sampleResponseUpdated1;sampleResponseDeleted1
      kafka:
        streams:
          binder:
            functions:
              sampleResponseCreated1:
                application-id: ${app.group}.${app.artifact-id}.sample-response.created.v1
              sampleResponseUpdated1:
                application-id: ${app.group}.${app.artifact-id}.sample-response.updated.v1
              sampleResponseDeleted1:
                application-id: ${app.group}.${app.artifact-id}.sample-response.deleted.v1

logging:
  level:
    com.netflix.config.sources.URLConfigurationSource: ERROR